keys:
  - &mbp_ssh age1xch7q5ksdd9tmszkwjxq55605h39hvh0u2zv6qxdsj0zc4hepf2s9xh902
  - &server_gpu_server_01 age1heagtpe467r8gv28d6hl3mtpnl9zu8cjuurt5xpf96jxp2d4s9rsek7get
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *mbp_ssh
        - *server_gpu_server_01
